project_id = "5db6d598-99de-437b-a03d-617c9f33bbce"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 9999
site_url = "https://5db6d598-99de-437b-a03d-617c9f33bbce.lovableproject.com"
additional_redirect_urls = ["https://5db6d598-99de-437b-a03d-617c9f33bbce.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_email_autoconfirm = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "كود التحقق من ملف - منصة الفريلانسرز"
content_path = "./supabase/templates/confirmation.html"

[functions.send-email]
verify_jwt = false